print("Harvey Bello Mirones")
print("Caigangan, Buenavista, Marinduque")
print("August 27, 1999")
print("Bachelor of Science in Infromation Technology")
print("Second Year, Section E")
print("Sleeping")
print("Eating")
print("Playing Video games")
print("Watching anime and reading manga")
print("bebe time")